# Cloudflare Tunnel Configuration
# Replace YOUR_TUNNEL_ID with your actual tunnel ID from Cloudflare

tunnel: 53d1c06b-1ebd-4bef-b5e4-f165bda8f988
credentials-file: /home/muarrikh/.cloudflared/53d1c06b-1ebd-4bef-b5e4-f165bda8f988.json

# Ingress rules - routes traffic to local services
ingress:
  # Main dashboard
  - hostname: log.myghty.cloud
    service: http://localhost:3003

  # API backend
  - hostname: log-api.myghty.cloud
    service: http://localhost:8000

  # Kafka UI (optional - for admin access)
  - hostname: kafka-ui.myghty.cloud
    service: http://localhost:8088

  # Kibana (optional - for advanced log analysis)
  - hostname: kibana.myghty.cloud
    service: http://localhost:5602

  # Spark UI (optional - for monitoring Spark jobs)
  - hostname: spark.myghty.cloud
    service: http://localhost:8082

  # Catch-all rule (required)
  - service: http_status:404

# Logging configuration
loglevel: info
logfile: /var/log/cloudflared.log

# Connection settings
retries: 3
retry-interval: 30s
grace-period: 30s

# Metrics (optional)
metrics: 0.0.0.0:8182